name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: CMPUT301Project

    - name: Build with Gradle
      working-directory: CMPUT301Project
      run: ./gradlew build

    - name: Run Unit Tests
      working-directory: CMPUT301Project
      run: ./gradlew test --rerun-tasks

    - name: Publish Test Summary Results
      run: npx github-actions-ctrf app/build/reports/tests/testDebugUnitTest.json
